### PR TITLE
adding 0.18.1 release announcement

### PR DESCRIPTION
**Pull request by heuermh**
Sorry, something looks not right about this pull request, maybe I'm not doing it against the right base?

### CODE REVIEW

**Comment by heuermh** [comment]
Ping @massie @fnothaft

**Comment by fnothaft** [comment]
Your source branch is a hybrid of the source and master branches...? How did? What? ;)

If you're around, perhaps let's get on IRC and sort this out.

**Comment by heuermh** [comment]
Yup, "What?" is about right.  I'll jump on IRC in a sec.

**Comment by massie** [comment]
Octopress creates a `_deploy` directory which is a git repo (pointing to the `master` branch). The `master` branch is the content that github serves. You should double-check that you have `_deploy` in your `.gitignore` and don't check anything in there (that is handled by the `rake` commands).

The `_deploy` directory is created when you run `rake generate`.

**Comment by massie** [comment]
You are using the correct base -- changes should be to the `source` branch.

**Comment by massie** [comment]
This looks good to me. Nice release announcement.

**Comment by heuermh** [comment]
Thanks @massie, I had some trouble with git that @fnothaft helped clear up.

**Pull request closed without merging**
