### PR TITLE
Clustering genomes post

### PR DESCRIPTION
**Pull request by xtordoir**
Hi!

Here is the post about the clustering of genomes, it all fun!. Let us know what you think!

Xavier / Andy

### CODE REVIEW

**Comment by fnothaft** [comment]
This looks great! Can you squash the commits down?

**Comment by xtordoir** [comment]
I actually see only one commit ;)

**Comment by fnothaft** [comment]
Awesome! Merged. Thanks @xtordoir and @andypetrella.

**Comment by fnothaft** [comment]
I will deploy this shortly.

**Comment by fnothaft** [comment]
I've deployed this; it should show up online shortly.

**Comment by fnothaft** [comment]
And, tis live: http://bdgenomics.org/blog/2015/02/02/scalable-genomes-clustering-with-adam-and-spark/

**Pull request merged**
